import React, { useState,useEffect } from 'react';
import { CheckCircle, Download, Share2, BarChart3, AlertCircle, Edit3, Users, Lightbulb,ArrowLeft,MessageCircle, Sparkle, Sparkles,} from 'lucide-react';
import jsPDF from "jspdf"
import { useLocation, useNavigate } from "react-router-dom";

const Result=()=>{
  const { state } = useLocation();
  const navigate = useNavigate();

  useEffect(() => {
    if (!state?.result) {
      navigate("/");
    }
  }, [state, navigate]);
  
  if (!state?.result) return null;
  
  const { result } = state;
  const [downloadingPDF, setDownloadingPDF] = useState(false)

  const downloadPDF = () => {
    if (!result) return
    setDownloadingPDF(true)
  
    try {
      const doc = new jsPDF()
      const lineHeight = 10
      let y = 10
      const margin = 10
      const pageHeight = doc.internal.pageSize.height
  
      // Helper function to handle long sections
      const addSection = (title, content) => {
        if (y + lineHeight > pageHeight - margin) {
          doc.addPage()
          y = margin
        }
  
        doc.setFontSize(12)
        doc.text(title, margin, y)
        y += lineHeight
  
        const lines = doc.splitTextToSize(content || "N/A", 180)
  
        lines.forEach((line) => {
          if (y + lineHeight > pageHeight - margin) {
            doc.addPage()
            y = margin
          }
          doc.text(line, margin, y)
          y += lineHeight
        })
  
        y += lineHeight // spacing after section
      }
  
      // Title
      doc.setFontSize(16)
      doc.text("PITCHPERFECT AI - ANALYSIS REPORT", margin, y)
      y += lineHeight
  
      // Date
      doc.setFontSize(11)
      doc.text(`Generated on: ${new Date().toLocaleDateString()}`, margin, y)
      y += lineHeight * 2
  
      // Overall Score
      doc.text(`OVERALL SCORE: ${result.overallScore}/10`, margin, y)
      y += lineHeight * 2
  
      // Scoring Breakdown
      doc.setFontSize(12)
      doc.text("DETAILED SCORING BREAKDOWN:", margin, y)
      y += lineHeight
  
      Object.entries(result.scores).forEach(([category, score]) => {
        if (y + lineHeight > pageHeight - margin) {
          doc.addPage()
          y = margin
        }
        doc.text(`${capitalize(category)}: ${score}/10`, margin, y)
        y += lineHeight
      })
  
      y += lineHeight
  
      // Add sections (full text shown, paginated properly)
      addSection("KEY STRENGTHS:", result.analysis.strengths)
      addSection("AREAS FOR IMPROVEMENT:", result.analysis.weaknesses)
      addSection("ACTIONABLE RECOMMENDATIONS:", result.analysis.recommendations)
      addSection("POTENTIAL INVESTOR QUESTIONS:", result.analysis.investorQuestions)
      addSection("KEY INSIGHTS:", result.analysis.insights)
  
      // Footer
      const footer = [
        "---",
        "Generated by PitchPerfect AI",
        "© 2024 PitchPerfect AI - AI-powered pitch analysis & optimization",
        "For more information, visit: https://pitchperfect.ai"
      ]
  
      footer.forEach((line) => {
        if (y + lineHeight > pageHeight - margin) {
          doc.addPage()
          y = margin
        }
        doc.setFontSize(10)
        doc.text(line, margin, y)
        y += lineHeight
      })
  
      doc.save(`pitch-analysis-report-${new Date().toISOString().split("T")[0]}.pdf`)
    } catch (error) {
      console.error("PDF download error:", error)
      setErrors({ general: "Failed to download report. Please try again." })
    } finally {
      setDownloadingPDF(false)
    }
  }
  const capitalize = (str) => str.charAt(0).toUpperCase() + str.slice(1)
  
  const getScoreColor = (score) => {
    const numScore = Number.parseFloat(score)
    if (numScore >= 8.5) return "text-green-600 bg-green-50 border-green-200"
    if (numScore >= 7.0) return "text-blue-600 bg-blue-50 border-blue-200"
    if (numScore >= 5.5) return "text-yellow-600 bg-yellow-50 border-yellow-200"
    return "text-red-600 bg-red-50 border-red-200"
  }

  const getScoreIcon = (score) => {
    const numScore = Number.parseFloat(score)
    if (numScore >= 8.5) return "🌟"
    if (numScore >= 7.0) return "⭐"
    if (numScore >= 5.5) return "⚡"
    return "🔄"
  }

    return(
      <>
          {result && (
            
          <div className="bg-white rounded-2xl shadow-2xl border border-slate-200/60 overflow-hidden animate-in slide-in-from-bottom-4 duration-500">
            <header className="bg-white/95 backdrop-blur-md border-b border-slate-200/60 shadow-sm flex-shrink-0">
        <div className="px-4 sm:px-6 lg:px-8 py-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <button
                onClick={() => navigate('/')}
                className="flex items-center gap-2 px-3 py-2 text-slate-600 hover:text-slate-800 hover:bg-slate-100 rounded-lg transition-all duration-200"
              >
                <ArrowLeft className="w-4 h-4" />
                <span className="text-sm font-medium hidden sm:inline">Back to Home</span>
              </button>
              
              <div className="flex items-center gap-3">
                <div className="bg-gradient-to-r from-green-600 to-emerald-600 p-2 rounded-xl shadow-lg">
                  <Sparkles className="w-5 h-5 text-white" />
                </div>
                <div>
                  <h1 className="text-lg sm:text-xl font-bold bg-gradient-to-r from-green-600 to-emerald-600 bg-clip-text text-transparent">
                  PitchPerfect AI - Analysis Report
                  </h1>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>
      
            <div className="bg-gradient-to-r from-emerald-600 via-green-600 to-teal-600 px-6 sm:px-8 py-6">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-xl font-semibold text-white flex items-center gap-3">
                    <CheckCircle className="w-6 h-6" />
                    Pitch Analysis Report
                  </h3>
                  <p className="text-emerald-100 mt-1">Analysis completed • Comprehensive 10-point evaluation</p>
                </div>
                <div className="flex gap-2">
                  <button
                    onClick={downloadPDF}
                    disabled={downloadingPDF}
                    className="bg-white/20 hover:bg-white/30 text-white p-2 rounded-lg transition-colors duration-200 disabled:opacity-50"
                  >
                    {downloadingPDF ? (
                      <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                    ) : (
                      <Download className="w-5 h-5" />
                    )}
                  </button>
                  <button className="bg-white/20 hover:bg-white/30 text-white p-2 rounded-lg transition-colors duration-200">
                    <Share2 className="w-5 h-5" />
                  </button>
                </div>
              </div>
            </div>

            <div className="p-6 sm:p-8 space-y-8">
              {/* Enhanced Overall Score */}
              <div className="text-center mb-8">
                <div className="inline-flex items-center gap-4 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-2xl p-8 border border-blue-100">
                  <div className="text-6xl">{getScoreIcon(result.overallScore)}</div>
                  <div>
                    <div className="text-4xl font-bold text-blue-600 mb-2">{result.overallScore}/10</div>
                    <p className="text-blue-700 font-semibold">Overall Score</p>
                    <p className="text-sm text-blue-600 mt-1">
                      {Number.parseFloat(result.overallScore) >= 8.5
                        ? "Excellent pitch!"
                        : Number.parseFloat(result.overallScore) >= 7.0
                          ? "Strong foundation"
                          : Number.parseFloat(result.overallScore) >= 5.5
                            ? "Good potential"
                            : "Needs improvement"}
                    </p>
                  </div>
                </div>
              </div>

              {/* Detailed Scoring Breakdown */}
              <div className="bg-slate-50 rounded-xl p-6 border border-slate-200">
                <h4 className="font-semibold text-slate-800 mb-6 flex items-center gap-2">
                  <BarChart3 className="w-5 h-5 text-slate-600" />
                  Detailed Scoring Breakdown
                </h4>

                <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-8">
                  {Object.entries(result.scores).map(([category, score]) => (
                    <div key={category} className={`p-4 rounded-xl border ${getScoreColor(score)}`}>
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-medium capitalize">{category}</span>
                        <span className="text-lg font-bold">{score}/10</span>
                      </div>
                      <div className="w-full bg-white/50 rounded-full h-2">
                        <div
                          className={`h-2 rounded-full transition-all duration-1000 ${
                            Number.parseFloat(score) >= 8.5
                              ? "bg-green-500"
                              : Number.parseFloat(score) >= 7.0
                                ? "bg-blue-500"
                                : Number.parseFloat(score) >= 5.5
                                  ? "bg-yellow-500"
                                  : "bg-red-500"
                          }`}
                          style={{ width: `${(Number.parseFloat(score) / 10) * 100}%` }}
                        />
                      </div>
                    </div>
                  ))}
                </div>

                {/* Paragraph-Style Analysis */}
                <div className="space-y-8">
                  {/* Strengths */}
                  <div className="bg-green-50 rounded-xl p-6 border border-green-100">
                    <h5 className="font-semibold text-green-800 mb-4 flex items-center gap-2">
                      <CheckCircle className="w-5 h-5 text-green-600" />
                      Key Strengths
                    </h5>
                    <p className="text-green-700 leading-relaxed text-sm">{result.analysis.strengths}</p>
                  </div>

                  {/* Areas for Improvement */}
                  <div className="bg-red-50 rounded-xl p-6 border border-red-100">
                    <h5 className="font-semibold text-red-800 mb-4 flex items-center gap-2">
                      <AlertCircle className="w-5 h-5 text-red-600" />
                      Areas for Improvement
                    </h5>
                    <p className="text-red-700 leading-relaxed text-sm">{result.analysis.weaknesses}</p>
                  </div>

                  {/* Recommendations */}
                  <div className="bg-amber-50 rounded-xl p-6 border border-amber-100">
                    <h5 className="font-semibold text-amber-800 mb-4 flex items-center gap-2">
                      <Edit3 className="w-5 h-5 text-amber-600" />
                      Actionable Recommendations
                    </h5>
                    <p className="text-amber-700 leading-relaxed text-sm">{result.analysis.recommendations}</p>
                  </div>

                  {/* Potential Investor Questions */}
                  <div className="bg-purple-50 rounded-xl p-6 border border-purple-100">
                    <h5 className="font-semibold text-purple-800 mb-4 flex items-center gap-2">
                      <Users className="w-5 h-5 text-purple-600" />
                      Potential Investor Questions
                    </h5>
                    <p className="text-purple-700 leading-relaxed text-sm">{result.analysis.investorQuestions}</p>
                  </div>

                  {/* Key Insights */}
                  <div className="bg-blue-50 rounded-xl p-6 border border-blue-100">
                    <h5 className="font-semibold text-blue-800 mb-4 flex items-center gap-2">
                      <Lightbulb className="w-5 h-5 text-blue-600" />
                      Key Insights
                    </h5>
                    <p className="text-blue-700 leading-relaxed text-sm">{result.analysis.insights}</p>
                  </div>
                </div>
              </div>

              {/* Enhanced Action Buttons */}
              <div className="flex flex-col sm:flex-row gap-4 pt-6 border-t border-slate-200">
                <button
                  onClick={downloadPDF}
                  disabled={downloadingPDF}
                  className="flex-1 bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-700 hover:to-indigo-700 text-white px-6 py-3 rounded-xl font-semibold transition-all duration-200 flex items-center justify-center gap-2 hover:scale-105 disabled:opacity-50 disabled:scale-100"
                >
                  {downloadingPDF ? (
                    <>
                      <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                      Generating PDF...
                    </>
                  ) : (
                    <>
                      <Download className="w-5 h-5" />
                      Download PDF Report
                    </>
                  )}
                </button>
                
                <button
                  onClick={() => {
                    navigate("/"); 
                  }}
                  className="sm:w-auto bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 px-6 py-3 rounded-xl font-semibold transition-all duration-200 hover:scale-105"
                >
                  Analyze Another
                </button>
              </div>
            </div>
          </div>
        )}
      </>
    );
};
export default Result;